name: Archive

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archive:
    runs-on: ubuntu-latest

    env:
      PACKAGE: HandyNotes_Achievements
      TOC: HandyNotes_Achievements.toc
      ARCHIVE: HandyNotes-Achievements.zip

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: collectivize
        run: |
          tr -d '\r' < $TOC | sed -e 's/#.*//;/^$/d' | tr '\n' '\0' | cpio -0pdv --quiet .release/$PACKAGE
          cp CHANGELOG.txt $TOC .release/$PACKAGE/

      - name: archive
        working-directory: .release
        run: zip -r $ARCHIVE $PACKAGE

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARCHIVE }}
          path: .release/${{ env.ARCHIVE }}
