name: Derive

on:
  workflow_dispatch:

jobs:
  # TODO move node/coffeescript dependency into the cloud
  achievement_locations:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install nodejs npm

      - name: npm
        run: |
          cd Libs/AchievementLocations
          npm install

      - name: derive
        run: |
          cd Libs/AchievementLocations
          coffee make.coffee
          # TODO inherit version from HandyNotes_Achievements.toc
          # TODO commit changes
          git diff
