name: Derive

on:
  workflow_dispatch:

jobs:
  achievement_locations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: node_modules
        run: npm install
        working-directory: Libs/AchievementLocations

      - name: derive
        run: node_modules/.bin/coffee make.coffee
        working-directory: Libs/AchievementLocations

      - name: compare
        run: git diff
        working-directory: Libs/AchievementLocations

