name: Derive

on:
  workflow_dispatch:

jobs:
  achievement_locations:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install nodejs npm

      - name: node_modules
        run: /usr/bin/npm install
        working-directory: Libs/AchievementLocations

      - name: derive
        run: /usr/bin/coffee make.coffee
        working-directory: Libs/AchievementLocations

      - name: compare
        run: /usr/bin/git diff
        working-directory: Libs/AchievementLocations

