# borrowing liberally from https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

name: CI

on:
  push:
    tags:
      - '**'
    branches: [ master ]
  pull_request:
    tags:
      - '**'
    branches: [ master ]

jobs:
  derive:
    runs-on: ubuntu-latest
    steps:
      - name: tbd
        run: true

  package:
    needs: derive
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
      APP: HandyNotes-Achievements
      PACKAGE: HandyNotes_Achievements
      TOC: ${{ env.PACKAGE }}.toc
      CHANGELOG: CHANGELOG.txt
      CHANGELOG_TYPE: markdown
      RELEASE_TYPE: alpha
      RELEASE: .release

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: collectivize
        run: |
          sed -e 's/#.*//' $TOC | cpio -pdv --quiet $RELEASE/$PACKAGE
          cp $CHANGELOG $TOC $RELEASE/$PACKAGE/

      - name: version
        run: |
          sed -ne 's/^\#\# Version: //p' $TOC | tr -d '\n' > $RELEASE/version
          echo "version $(cat version)"

      - name: game_version
        run: |
          sed -ne '/^\#\# Interface/{s/^\#\# Interface: \([0-9]*\)\([0-9][0-9]\)\([0-9][0-9]\)/\1.\2.\3/;s/\.0/./gp;q;}' $TOC | tr -d '\n' > $RELEASE/game_version
          echo "game_version $(cat game_version)"

      - name: archive
        working-directory: release
        run: |
          VERSION=$(cat version)
          ARCHIVE=${APP}-${VERSION}.zip
          zip -r $ARCHIVE $PACKAGE
          echo $ARCHIVE > archive
          echo "archive $ARCHIVE"

      - name: upload
        working-directory: release
        run: |
          VERSION=$(cat version)
          GAME_VERSION=$(cat game_version)
          ARCHIVE=$(cat archive)
          DISPLAY_NAME=v$VERSION
          CHANGELOG_QUOTED=$(cat $CHANGELOG | sed -e 's/"/\\"/g')
          echo "{" \"displayName\":\""$DISPLAY_NAME"\", \"gameVersions\":\""$GAME_VERSION"\", \"releaseType\":\""$RELEASE_TYPE"\", \"changelogType\":\""$CHANGELOG_TYPE"\", \"changelog\":\""$CHANGELOG_QUOTED"\" "}" > metadata
          cat metadata | curl -H "x-api-token: $CURSEFORGE_API_TOKEN" -F "metadata=<-" -F "file=@$ARCHIVE" "https://wow.curseforge.com/api/projects/$CURSEFORGE_PROJECT_ID/upload-file"
