# borrowing liberally from https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

name: CI

on:
  push:
    tags:
      - '**'
    branches: [ master ]
  pull_request:
    tags:
      - '**'
    branches: [ master ]

jobs:
  derive:
    runs-on: ubuntu-latest
    steps:
      - name: tbd
        run: true

  package:
    needs: derive
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
      APP: HandyNotes-Achievements
      PACKAGE: HandyNotes_Achievements

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: collectivize
        run: |
          mkdir -p release/$PACKAGE
          cp CHANGELOG.txt HandyNotes_Achievements* release/$PACKAGE/
          cp -r Locales release/$PACKAGE/
          find Libs -depth -name '.git*' -prune -o -name Makefile -prune -o -name 'package*.json' -prune -o -name node_modules -prune -o -name '*.coffee' -prune -o -print0 | cpio -0pdv --quiet release/$PACKAGE

      - name: debug_release_dir
        run: find release/$PACKAGE -type f

      - name: version
        run: sed -ne 's/^\#\# Version: //p' HandyNotes_Achievements.toc > release/version

      - name: game_version
        run: sed -ne '/^\#\# Interface/{s/^\#\# Interface: \([0-9]*\)\([0-9][0-9]\)\([0-9][0-9]\)/\1.\2.\3/;s/\.0/./gp;q;}' HandyNotes_Achievements.toc > release/game_version

      - name: archive
        working-directory: release
        run: |
          VERSION=$(cat version)
          ARCHIVE=${APP}-${VERSION}.zip
          zip -r $ARCHIVE $PACKAGE
          echo $ARCHIVE > archive

      - name: upload
        working-directory: release
        run: |
          VERSION=$(cat version)
          GAME_VERSION=$(cat game_version)
          ARCHIVE=$(cat archive)
          echo "archive $ARCHIVE"
          DISPLAY_NAME=v$VERSION
          RELEASE_TYPE=alpha
          CHANGELOG_TYPE=markdown
          CHANGELOG=tbd
          echo "{" \"displayName\":\""$DISPLAY_NAME"\", \"gameVersions\":\""$GAME_VERSION"\", \"releaseType\":\""$RELEASE_TYPE"\", \"changelogType\":\""$CHANGELOG_TYPE"\", \"changelog\":\""$CHANGELOG"\" "}" > metadata
          echo "metadata:"
          cat metadata
          echo cat metadata \| curl -H "x-api-token: $CURSEFORGE_API_TOKEN" -F "metadata=<-" -F "file=@$ARCHIVE" "https://wow.curseforge.com/api/projects/$CURSEFORGE_PROJECT_ID/upload-file"
