# borrowing liberally from https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

name: Release

on:
  push:
    tags:
      - '**'
    branches: [ master ]
  pull_request:
    tags:
      - '**'
    branches: [ master ]

jobs:
  release:
    runs-on: debian-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      APP: HandyNotes-Achievements
      BASE: HandyNotes_Achievements

    steps:
      - name: checkout_dir_wrapped
        uses: actions/checkout@v2
        with:
          path: ${{ env.BASE }}
          submodules: true

      - name: secretstest
        run: echo "secret $TEST_SECRET"

      - name: zip
        run: |
          echo "base $BASE"
          ls -la $BASE
          VERSION=$(sed -ne 's/^\#\# Version: //p' $BASE/HandyNotes_Achievements.toc)
          echo "version $VERSION"
          zip -r ${APP}-${VERSION}.zip $BASE/HandyNotes_Achievements* $BASE/Libs/* $BASE/Locales/* $BASE/CHANGELOG.txt -x '*/Makefile' -x '*/package*.json' -x '*/node_modules/*' -x '*.coffee' -x '*/.git*'
