# borrowing liberally from https://github.com/BigWigsMods/packager

name: Release

#on:
#  push:
#    tags:
#      - '**'
#    branches: [ master ]
#  pull_request:
#    tags:
#      - '**'
#    branches: [ master ]

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: alpha, beta, or release
        default: alpha

jobs:
  package:
    runs-on: ubuntu-latest

    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
      APP: HandyNotes-Achievements
      PACKAGE: HandyNotes_Achievements
      TOC: HandyNotes_Achievements.toc
      CHANGELOG: CHANGELOG.txt
      CHANGELOG_TYPE: markdown
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}
      RELEASE: .release

    steps:
      - name: deps
        run: |
          #sudo apt-get -y update
          sudo apt-get -y install jq

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: collectivize
        run: |
          tr -d '\r' < $TOC | sed -e 's/#.*//;/^$/d' | tr '\n' '\0' | cpio -0pdv --quiet $RELEASE/$PACKAGE
          cp $CHANGELOG $TOC $RELEASE/$PACKAGE/
          cp $CHANGELOG $RELEASE/changelog

      - name: version
        run: |
          sed -ne 's/^\#\# Version: //p' $TOC | tr -d '\r\n' > $RELEASE/version
          echo "version $(cat $RELEASE/version)"

      - name: game_version
        run: |
          sed -ne '/^\#\# Interface/{s/^\#\# Interface: \([0-9]*\)\([0-9][0-9]\)\([0-9][0-9]\)/\1.\2.\3/;s/\.0/./gp;q;}' $TOC | tr -d '\r\n' > $RELEASE/game_version
          echo "game_version $(cat $RELEASE/game_version)"

      - name: game_version_id
        run: |
          GAME_VERSION=$(cat $RELEASE/game_version)
          curl -s -H "x-api-token: $CURSEFORGE_API_TOKEN" https://wow.curseforge.com/api/game/versions | jq "map(select(.name==\"$GAME_VERSION\")) | .[0] | .id" | tr -d '\n\r' > $RELEASE/game_version_id
          echo "game_version_id $(cat $RELEASE/game_version_id)"

      - name: archive
        working-directory: ${{ env.RELEASE }}
        run: |
          pwd
          VERSION=$(cat version)
          ARCHIVE=${APP}-${VERSION}.zip
          zip -r $ARCHIVE $PACKAGE
          echo $ARCHIVE > archive
          echo "archive $ARCHIVE"

      - name: upload
        working-directory: ${{ env.RELEASE }}
        run: |
          VERSION=$(cat version)
          GAME_VERSION_ID=$(cat game_version_id)
          ARCHIVE=$(cat archive)
          DISPLAY_NAME=v$VERSION
          CHANGELOG_QUOTED=$(cat changelog | sed -e 's/"/\\"/g')
          echo "{\"displayName\":\"$DISPLAY_NAME\", \"gameVersions\":[$GAME_VERSION_ID], \"releaseType\":\"$RELEASE_TYPE\", \"changelogType\":\"$CHANGELOG_TYPE\", \"changelog\":\"$CHANGELOG_QUOTED\"}" > metadata
          cat metadata
          cat metadata | curl -s -H "x-api-token: $CURSEFORGE_API_TOKEN" -F "metadata=<-" -F "file=@$ARCHIVE" "https://wow.curseforge.com/api/projects/$CURSEFORGE_PROJECT_ID/upload-file"

# TODO parse upload status
# TODO fail on redundant version + release type combo?
# TODO or overwrite redundant version + release type combo?
# TODO or auto subminor version bump?
# TODO run on push of new tag
# TODO release to github?
